# TODO delete? depended on by opt-out-export-test-integration.yml
name: opt-out-export test (impl) deploy

on:
  workflow_call: # Allow for call from integration test
  workflow_dispatch:

jobs:
  deploy:
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    runs-on: self-hosted
    environment: test
    defaults:
      run:
        working-directory: ./attribution-data-file-share
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: cmsgov/cdap/actions/aws-params-env-action@main
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        with:
          params: |
            ARTIFACTORY_URL=/artifactory/url
            ARTIFACTORY_USER=/artifactory/user
            ARTIFACTORY_PASSWORD=/artifactory/password
      - name: Build opt-out-export zip file
        run: ../gradlew buildZip
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/delegatedadmin/developer/ab2d-test-github-actions
      - name: Upload and reload
        run: |
          aws s3 cp --no-progress build/distributions/attributionDataShare.zip \
            s3://ab2d-test-opt-out-export-function/function-${{ github.sha }}.zip
          aws lambda update-function-code --function-name ab2d-test-opt-out-export \
            --s3-bucket ab2d-test-opt-out-export-function --s3-key function-${{ github.sha }}.zip
