name: tofu-plan

on:
  workflow_call:
    inputs:
      environment:
        description: AB2D environment
        required: true
        type: string
      api_image_tag:
        description: ECR image tag for api service
        required: true
        type: string
      contracts_image_tag:
        description: ECR image tag for contracts service
        required: true
        type: string
      events_image_tag:
        description: ECR image tag for events service
        required: true
        type: string
      worker_image_tag:
        description: ECR image tag for worker service
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: AB2D environment
        required: true
        type: choice
        options:
          - dev
          - test
          - sandbox
          - prod
      api_image_tag:
        description: ECR image tag for api service
        required: true
        type: string
      contracts_image_tag:
        description: ECR image tag for contracts service
        required: true
        type: string
      events_image_tag:
        description: ECR image tag for events service
        required: true
        type: string
      worker_image_tag:
        description: ECR image tag for worker service
        required: true
        type: string

concurrency:
  group: tofu-plan-or-apply

env:
  TENV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  plan:
    permissions:
      contents: read
      id-token: write
    runs-on: codebuild-ab2d-${{github.run_id}}-${{github.run_attempt}}
    env:
      APP: ab2d
      ENV: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: sigstore/cosign-installer@d58896d6a1865668819e1d91763c7751a165e159  # v3.9.2
      - uses: cmsgov/cdap/actions/setup-tenv@8343fb96563ce4b74c4dececee9b268f42bd4a40
      - uses: cmsgov/cdap/actions/setup-sops@84a6bcee5b70d63c44f8fec4f9b542cb5ec29a54
      - uses: cmsgov/cdap/actions/setup-yq@328406d6e1d435b4e3da598bcdab22e576c3945e
      - uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
        with:
          role-to-assume: arn:aws:iam::${{ contains(fromJSON('["dev", "test"]'), inputs.environment) && secrets.NON_PROD_ACCOUNT || secrets.PROD_ACCOUNT }}:role/delegatedadmin/developer/ab2d-${{ inputs.environment }}-github-actions
          aws-region: ${{ vars.AWS_REGION }}
      - if: ${{ contains(fromJSON('["test", "prod"]'), inputs.environment) == true }}
        name: tofu plan - bootstrap
        working-directory: ops/services/00-bootstrap/
        run: |
          tofu init -var=parent_env=$ENV -reconfigure
          tofu workspace select -var=parent_env=$ENV -or-create=true $ENV
          tofu plan
      - name: tofu plan - config
        working-directory: ops/services/10-config/
        run: |
          tofu init -var=parent_env=$ENV -reconfigure
          tofu workspace select -var=parent_env=$ENV -or-create=true $ENV
          tofu plan
      - name: tofu plan - core
        working-directory: ops/services/10-core/
        run: |
          tofu init -var=parent_env=$ENV -reconfigure
          tofu workspace select -var=parent_env=$ENV -or-create=true $ENV
          tofu plan
      - name: tofu plan - web
        working-directory: ops/services/15-web/
        run: |
          tofu init -var=parent_env=$ENV -reconfigure
          tofu workspace select -var=parent_env=$ENV -or-create=true $ENV
          tofu plan
      - name: tofu plan - microservices
        working-directory: ops/services/20-microservices/
        run: |
          tofu init -var=parent_env=$ENV -reconfigure
          tofu workspace select -var=parent_env=$ENV -or-create=true $ENV
          tofu plan -var=contracts_service_image_tag=${{ inputs.contracts_image_tag }} -var=events_service_image_tag=${{ inputs.events_image_tag }}
      - name: tofu plan - api
        working-directory: ops/services/30-api/
        run: |
          tofu init -var=parent_env=$ENV -reconfigure
          tofu workspace select -var=parent_env=$ENV -or-create=true $ENV
          tofu plan -var=api_service_image_tag=${{ inputs.api_image_tag }}
      - name: tofu plan - lambda
        working-directory: ops/services/30-lambda/
        run: |
          tofu init -var=parent_env=$ENV -reconfigure
          tofu workspace select -var=parent_env=$ENV -or-create=true $ENV
          tofu plan
      - name: tofu plan - worker
        working-directory: ops/services/30-worker/
        run: |
          tofu init -var=parent_env=$ENV -reconfigure
          tofu workspace select -var=parent_env=$ENV -or-create=true $ENV
          tofu plan -var=worker_service_image_tag=${{ inputs.worker_image_tag }}
